# Generated by Django 4.1.3 on 2022-12-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freeforall', '0002_invitaciones_liga_login_usuarios_evento_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='Municipio',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='feha_fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_de_nacimiento',
            field=models.DateTimeField(),
        ),
    ]
