# Generated by Django 4.1.3 on 2022-12-05 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Freeforall', '0003_alter_evento_municipio_alter_evento_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='id_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Freeforall.evento'),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Freeforall.usuarios'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='id_liga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Freeforall.liga'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Freeforall.usuarios'),
        ),
    ]
