# Generated by Django 4.1.3 on 2022-12-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freeforall', '0005_usuarios_clave_usuarios_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.CharField(choices=[('A', 'Administrador'), ('E', 'Espectador')], default='O', max_length=100),
        ),
    ]
