# Generated by Django 4.1.3 on 2022-12-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freeforall', '0006_alter_usuarios_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='estado',
            field=models.CharField(default='O', max_length=100),
        ),
    ]
