# Generated by Django 4.1.3 on 2022-12-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freeforall', '0007_usuarios_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='foto',
            field=models.ImageField(default='Freeforall/fotos/default.webp', upload_to='fotos'),
        ),
    ]
