# Generated by Django 4.1.3 on 2022-12-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freeforall', '0008_usuarios_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='foto',
        ),
        migrations.AddField(
            model_name='evento',
            name='foto',
            field=models.ImageField(default='Freeforall/fotos/default.webp', upload_to='fotos'),
        ),
    ]
