# Generated by Django 4.1.3 on 2022-12-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freeforall', '0009_remove_usuarios_foto_evento_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='foto',
            field=models.ImageField(default='Freeforall/fotos/default.webp', upload_to='Freeforall/fotos'),
        ),
    ]
