# Generated by Django 4.1.3 on 2022-12-08 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Freeforall', '0011_alter_evento_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='genero',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
    ]
