# Generated by Django 4.1.3 on 2022-12-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freeforall', '0013_remove_evento_id_invitaciones_alter_usuarios_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='estado',
            field=models.CharField(default='Activado', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='estado',
            field=models.CharField(default='Activado', max_length=100),
        ),
    ]
