# Generated by Django 4.1.3 on 2022-12-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freeforall', '0014_evento_estado_alter_usuarios_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='competidor',
            field=models.ManyToManyField(blank=True, related_name='competidor', to='Freeforall.usuarios'),
        ),
        migrations.AddField(
            model_name='evento',
            name='espectador',
            field=models.ManyToManyField(blank=True, related_name='espectador', to='Freeforall.usuarios'),
        ),
    ]
