# Generated by Django 4.1.3 on 2022-12-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freeforall', '0016_alter_evento_competidor_alter_evento_espectador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='competidor',
            field=models.ManyToManyField(blank=True, related_name='competidor', to='Freeforall.usuarios'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='espectador',
            field=models.ManyToManyField(blank=True, related_name='espectador', to='Freeforall.usuarios'),
        ),
    ]
