# Generated by Django 4.1.3 on 2022-12-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freeforall', '0017_alter_evento_competidor_alter_evento_espectador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='competidor',
            field=models.ManyToManyField(related_name='evento_competidor', to='Freeforall.usuarios'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='espectador',
            field=models.ManyToManyField(related_name='evento_espectador', to='Freeforall.usuarios'),
        ),
    ]
