# Generated by Django 4.1.3 on 2022-12-12 09:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Freeforall', '0018_alter_evento_competidor_alter_evento_espectador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='competidor',
            field=models.ManyToManyField(related_name='evento_competidor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evento',
            name='espectador',
            field=models.ManyToManyField(related_name='evento_espectador', to=settings.AUTH_USER_MODEL),
        ),
    ]
