# Generated by Django 4.1.3 on 2022-12-12 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Freeforall', '0020_remove_comentarios_hora_ingreso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='Comentarios',
            new_name='comentarios',
        ),
    ]
