# Generated by Django 4.1.3 on 2023-01-20 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Freeforall', '0022_alter_comentarios_id_comentarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='fecha_ingreso',
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='id_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Freeforall.evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='estado',
            field=models.CharField(choices=[('A', 'Activado'), ('D', 'Desactivado')], default='Activado', max_length=100),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto',
            field=models.ImageField(default='Freeforall/fotos/default.webp', upload_to='Freeforall/fotos'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='estado',
            field=models.CharField(choices=[('A', 'Activado'), ('D', 'Desactivado')], default='Activado', max_length=100),
        ),
    ]
